// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-8zcu7aXQvbpjSgXPBS81I7XYZBknQ2g',
    appId: '1:723796542944:web:f5b933554e038a1ee35785',
    messagingSenderId: '723796542944',
    projectId: 'explore-malaysia-52fe4',
    authDomain: 'explore-malaysia-52fe4.firebaseapp.com',
    storageBucket: 'explore-malaysia-52fe4.firebasestorage.app',
    measurementId: 'G-E51F654EN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzvs_PpnyyepyRjkJeriVZF8j7MxeIxGI',
    appId: '1:723796542944:android:8623c3b1ad4a33cbe35785',
    messagingSenderId: '723796542944',
    projectId: 'explore-malaysia-52fe4',
    storageBucket: 'explore-malaysia-52fe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiEsZNfLByC283aBu72ctsa6NnRVDUHDA',
    appId: '1:723796542944:ios:3111b97d5c211a53e35785',
    messagingSenderId: '723796542944',
    projectId: 'explore-malaysia-52fe4',
    storageBucket: 'explore-malaysia-52fe4.firebasestorage.app',
    iosBundleId: 'explore-malaysia-52fe4',
  );
}
